name: rolimoa-dev

services:
  client:
    build:
      context: .
      target: dev
    command: npm run dev --workspace=packages/client -- --host
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: ./packages/client
        target: /rolimoa/packages/client
      - type: volume
        source: client_node_modules
        target: /rolimoa/packages/client/node_modules
    networks:
      - app-network

  server:
    build:
      context: .
      target: dev
    command: npm run dev --workspace=packages/server
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./packages/server
        target: /rolimoa/packages/server
      - type: volume
        source: server_node_modules
        target: /rolimoa/packages/server/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  client_node_modules:
  server_node_modules:
